CONTAINER Osplinedataspline
{
	NAME Osplinedataspline;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		SPLINE OSPLINEDATA_SPLINECURVE { }
		REAL OSPLINEDATA_WIDTH { UNIT METER; MIN 0.0; }
		REAL OSPLINEDATA_HEIGHT { UNIT METER; MIN 0.0; }
		LONG OSPLINEDATA_SUBDIVISION { MIN 2; MAX 1000; }
		SEPARATOR { LINE; }
	}
	INCLUDE Ospline;
}
