CONTAINER Osplinedataaxisspline
{
	NAME Osplinedataaxisspline;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL OSPLINEDATAAXIS_WIDTH { UNIT METER; MIN 0.0; }
		REAL OSPLINEDATAAXIS_HEIGHT { UNIT METER; MIN 0.0; }
		REAL OSPLINEDATAAXIS_OVERSHOOT { UNIT METER; }

		BOOL OSPLINEDATAAXIS_ARROWS {}
		REAL OSPLINEDATAAXIS_ARROW_HEIGHT { UNIT METER; MIN 0.0; }
		REAL OSPLINEDATAAXIS_ARROW_WIDTH { UNIT METER; MIN 0.0; }
		REAL OSPLINEDATAAXIS_ARROW_OVERSHOOT { UNIT METER; MIN 0.0; }
		
		SEPARATOR { LINE; }
	}
	INCLUDE Ospline;
}
