#ifndef OSPLINEDATAAXISSPLINE_H__
#define OSPLINEDATAAXISSPLINE_H__

enum
{
	OSPLINEDATAAXIS_WIDTH           = 10000, // FLOAT
	OSPLINEDATAAXIS_HEIGHT          = 10001, // FLOAT
	OSPLINEDATAAXIS_OVERSHOOT       = 10002, // FLOAT
	OSPLINEDATAAXIS_ARROWS          = 10003, // BOOL
	OSPLINEDATAAXIS_ARROW_HEIGHT    = 10004, // FLOAT
	OSPLINEDATAAXIS_ARROW_WIDTH     = 10005, // FLOAT
	OSPLINEDATAAXIS_ARROW_OVERSHOOT = 10006  // FLOAT
};

#endif // OSPLINEDATAAXISSPLINE_H__
