#ifndef OSPLINEDATASPLINE_H__
#define OSPLINEDATASPLINE_H__

enum
{
	OSPLINEDATA_SPLINECURVE = 10000,
	OSPLINEDATA_WIDTH       = 10001,
	OSPLINEDATA_HEIGHT      = 10002,
	OSPLINEDATA_SUBDIVISION = 10003
};

#endif // OSPLINEDATASPLINE_H__
