#ifndef OSPLINEDATASPLINE_H__
#define OSPLINEDATASPLINE_H__

enum
{
	OSPLINEDATA_SPLINECURVE = 10000, // SPLINEDATA
	OSPLINEDATA_WIDTH       = 10001, // FLOAT
	OSPLINEDATA_HEIGHT      = 10002, // FLOAT
	OSPLINEDATA_SUBDIVISION = 10003  // INT
};

#endif // OSPLINEDATASPLINE_H__
