enum
{
	IDS_OBJECTDATA_SPLINEDATASPLINE	= 10000,
	IDS_OBJECTDATA_SPLINEDATAAXISSPLINE,
	IDS_COMMANDDATA_SPLINEDATAVIS,
	IDH_COMMANDDATA_SPLINEDATAVIS,

	IDS_SPLINEDATAVIS_GROUPOBJ,
	IDS_SPLINEDATAVIS_SPLINEDATA_SWEEP,
	IDS_SPLINEDATAVIS_SPLINEDATA_OBJECT,
	IDS_SPLINEDATAVIS_SPLINEDATA_PROFILE,
	IDS_SPLINEDATAVIS_AXIS_SWEEP,
	IDS_SPLINEDATAVIS_AXIS_OBJECT,
	IDS_SPLINEDATAVIS_AXIS_PROFILE,
	IDS_SPLINEDATAVIS_TEXT_TEXTOBJECT,
	IDS_SPLINEDATAVIS_TEXT_EXTRUDEOBJECT,
	IDS_SPLINEDATAVIS_MAT_SPLINEDATA,
	IDS_SPLINEDATAVIS_MAT_AXIS,
	IDS_SPLINEDATAVIS_MAT_TEXT,
	IDS_SPLINEDATAVIS_TEXT_DEFAULT,

	_DUMMY_ELEMENT_
};
